rvm: 1.8.7
notifications:
env:
  - PUPPET_VERSION=2.7.11
  - PUPPET_VERSION=3.2.2
language: ruby
bundler_args: --without development
script: "rake spec SPEC_OPTS='--format documentation' && rake lint"
