language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
script: "bundle exec rake test"
rvm:
  - 1.8.7
  - 2.0.0
env:
  - PUPPET_VERSION="2.7.11"
  - PUPPET_VERSION="3.2.2"
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.7.0"
matrix:
  fast_finish: true
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 3.1.0"
    - rvm: 2.0.0
      env: PUPPET_VERSION="~> 2.7.0"
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.7.0"
notifications:
  email: false
